export const ActionTypes = {
    'FETCHPOSTS' : 'FETCHPOSTS',
    'FETCHCOMMENTS' : 'FETCHCOMMENTS',
    'FETCHUSERS' : 'FETCHUSERS',
    'FETCHALBUMS' : 'FETCHALBUMS',
    'FETCHTODOS': 'FETCHTODOS'
}