export const ActionTypes = {
    // 'FETCHBOOK': 'FETCHBOOK',
    // 'FETCHONEBOOK': 'FETCHONEBOOK'
    'FETCHPOSTS' : 'FETCHPOSTS',
    'FETCHCOMMENTS' : 'FETCHCOMMENTS',
    'FETCHUSERS' : 'FETCHUSERS',
    'FETCHALBUMS' : 'FETCHALBUMS',
    'FETCHTODOS': 'FETCHTODOS'
}